complete -c crm -x -a opp  -d "create a new opportunity"
complete -c crm -x -a help -d "display usage info"
complete -c crm -x -a open -d "choose current crm opportunity"
complete -c crm -x -a sync -d "save activity to git origin"
complete -c crm -x -a update -d "provide status updates on an opp"
